### PR TITLE
Update github repo 2020/04/17

### PR DESCRIPTION
**Pull request by monsieurnoir**
- Fixes a memory leak on iOS
- Fixes an issue with seeking in MP3s on iOS
- Adds support for ni-internal cmake tools and clang debugging
- Fixes a compile issue with clang in media_foundation_source.h

### CODE REVIEW

**Comment by marcrambo** [comment]
@monsieurnoir looks like the pipeline didn't run?

**Comment by monsieurnoir** [comment]
> @monsieurnoir looks like the pipeline didn't run?

Can you help me out on how to invoke it? Maybe rights restrictions? I also noticed that my access to the github interface here is limited with regards to requesting review from specific reviewers.. Could you double-check the repository settings?

**Comment by marcrambo** [comment]
It should have been triggered automatically. I just double checked with my account. I created a PR but the ci didn't start either. So I guess something has changed on the repo settings. Unfortunately I cannot look into it as I don't have full access to the repo anymore. By the way, this would be a good opportunity to unify the ci. Either migrating to azure or remove appveyor and do everything in travis, as they now also support windows (I don't know how good it is though)

**Comment by ni-mheppner** [comment]
Closing this pull request, as it is not up to date anymore and there have been administrative issues. For an updated version please refer to https://github.com/NativeInstruments/ni-media/pull/45.

**Pull request closed without merging**
